export default [
    {
      id: "1",
      categoryId: "1",
      name: "Apple iPhone 5c",
      brand: "Apple",
      description: "The iPhone 5c leads the series for being the first Apple smartphone that comes in multiple vibrant shades. As opposed to the other devices from the brand, all of which stick to basic shades like black, white, silver, grey and gold, this device can be picked up in pink, yellow, blue and green, apart from white and is available with a memory capacity of 8GB. The device is best suited for people on the lookout for an advanced yet stylish smartphone, loaded with all the essential features.",
      price: 823,
      image: "/uploads/iphone5c-selection-hero-2013.png",
      cpu: "1.3GHz Apple A6",
      camera: "8mp f.2.4",
      size: "124.4mm x 59.2mm x 8.97mm",
      weight: "132 grams",
      display: "4.0 326 pixel density",
      battery: "1480 mAh",
      memory: "16GB"
    },
    {
      id: "2",
      categoryId: "1",
      name: "Apple iPhone 6",
      brand: "Apple",
      description: "Equipped with impressive features and decent specifications, the Apple iPhone 6 32GB is a perfect choice that is available at a starting price of $900. The phone offers a slip-free grip as it is light in weight and is easy to carry.",
      price: 953,
      image: "/uploads/51u6y9Rm8QL._SY300_.jpg",
      cpu: "1.4GHz Apple A8",
      camera: "8mp f/2.2",
      size: "138.1 x 67 x 6.9 mm",
      weight: "129g",
      display: "4.7 326 pixel density",
      battery: "1810 mAh",
      memory: "32GB"
    },
    {
      id: "3",
      categoryId: "4",
      name: "Lenovo A6000",
      brand: "Lenovo",
      description: "For smooth, responsive system performance that won't break the bank, the A6000 is superb. Boasting a 1.2Ghz 64-bit quad core Qualcomm® Snapdragon™ processor, it has the power to play music & video, run apps & games, and more - all without skipping a beat.",
      price: 764,
      image: "/uploads/_35%20(1).JPG",
      cpu: "Quad-core 1.2 GHz Cortex-A53",
      camera: "12 MP, f/2.1",
      size: "141 x 70 x 8.2 mm",
      weight: "128g",
      display: "5.0 294 pixel density",
      battery: "2300 mAh",
      memory: "8GB"
    },
    {
      id: "4",
      categoryId: "5",
      name: "Nokia Lumia 1520",
      brand: "Nokia",
      description: "The Nokia Lumia 1520 puts more in your pocket with a six-inch, full HD display, 20 megapixel PureView camera, and powerful quad-core 2.2 GHz Snapdragon 800 processor to power you through from day to night, making your day seamless for work, play, and everything else in between.",
      price: 544,
      image: "/uploads/Lumia1520-Front-Back-png.png",
      cpu: "Quad-core 2.2 GHz Krait 400",
      camera: "20 MP, f/2.4",
      size: "162.8 x 85.4 x 8.7 mm",
      weight: "209 grams",
      display: "6.0 367 pixel density",
      battery: "3400 mAh",
      memory: "32GB"
    },
    {
      id: "5",
      categoryId: "3",
      name: "HTC One",
      brand: "HTC",
      description: "Delivering breakthrough design and packed with the latest HTC Sense 6 experience, HTC Duo Camera for advanced imaging, and intuitive Motion Launch, the HTC One will deliver an unparalleled smartphone experience for 2014.",
      price: 614,
      image: "/uploads/htc-one-m7-802w-dual-sim-silver.jpg",
      cpu: "Quad-core 1.7 GHz Krait 300",
      camera: "4mp f/2.0",
      size: "137.4 x 68.2 x 9.3 mm",
      weight: "143 grams",
      display: "4.7 469 pixel density",
      battery: "2300 mAh",
      memory: "64GB"
    },
    {
      id: "6",
      categoryId: "2",
      name: "Samsung Galaxy S6",
      brand: "Samsung",
      description: "Samsung Galaxy S6 edge blurs the line between beauty and power. With its dual-curve glass display and flawless performance, it'll take your mobile",
      price: 912,
      image: "/uploads/Agnes_Case_for_Samsung_Galaxy_S6_(1)__92643_thumb.jpg",
      cpu: "Octa-core (4x2.1 GHz Cortex-A57 & 4x1.5 GHz Cortex-A53)",
      camera: "8mp (3264x2448)",
      size: "143.4 x 70.5 x 6.8 mm",
      weight: "138 grams",
      display: "5.1 577 pixel density",
      battery: "2550 mAh",
      memory: "128GB"
    }
  ]
  